### ISSUE TITLE
[Feature request] Command to reparse all comments in order to refresh the highlighting of code snippets

### ISSUE THREAD

**Issue by rebelC0der** [club-1/flarum-ext-server-side-highlight#1]
Issue:

When the extension is enabled, existing code snippets do not get highlighting.

To enable the syntax highlighting for the existing snippets, user needs to follow these steps:

1. Open a thread with the code snippet
2. Start the editing of that thread
3. Change any line or add a space (so there is any change in the thread)
4. Save the changes

Expected results:
Existing code snippets get syntax highlighting when the extension is enabled.

**Comment by n-peugnet** [comment]
This is not exactly a bug, this is by design. The messages need to be reparsed, as the block ID is determined while parsing. I am currently thinking about an extension that would provide some useful commands, like a `reparse` command as it would be also useful for all the other extensions that need to reparse the messages (e.g. https://github.com/club-1/flarum-ext-cross-references/issues/34)

**Comment by n-peugnet** [comment]
I just made a quick implementation of this command in https://github.com/club-1/flarum-ext-chore-commands.

It is not yet very well tested but I already corrected some mistakes I made along the way. I do absolutely not recommend to run it in production yet, but I would be interesting if you could make some testing on your end.
